(deftemplate alumno
	(multislot apellidos(type STRING)
			     (default ?NONE))
	(multislot nombre(type STRING)
			  (default ?NONE))
	(multislot miembros(type STRING))
	(slot miembrosMax(type INTEGER)
			   (range 1 4))
	(slot notaExamen(type INTEGER)
			(range 1 10))
	(slot notamMedia(type INTEGER)
			(range 1 10))
	(slot notaTrabajo(type INTEGER)
			(range 1 10))
)
