(deftemplate juego
	(slot fila(type STRING)
		  (default ?NONE))
	(slot columna(type INTEGER)
		     (default ?NONE))
	(slot casillas_ocupadas(type INTEGER)
		     (default ?NONE)
		     (range 1 4))
	(slot barco(type STRING)
		   (default ?NONE)
		   (allowed-strings "patrullera" "dragaminas" "fragata" "acorazado" "destructor" "portaaviones"))
	(slot estado(type STRING)
		    (default "indemne")
		    (allowed-strings "indemne" "tocado" "hundido"))
)))
